# Akihiro Motoki <amotoki@gmail.com>, 2017. #zanata
msgid ""
msgstr ""
"Project-Id-Version: horizon 13.0.0.0b2.dev91\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-03-26 08:19+0000\n"
"PO-Revision-Date: 2017-11-16 08:03+0000\n"
"Last-Translator: Akihiro Motoki <amotoki@gmail.com>\n"
"Language-Team: Japanese\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Zanata 3.9.6\n"
"Plural-Forms: nplurals=1; plural=0\n"

#: openstack_auth/backend.py:57
msgid "The authentication token issued by the Identity service has expired."
msgstr "Identity サービスにより発行された認証トークンの期限が切れました。"

#: openstack_auth/backend.py:109
msgid ""
"No authentication backend could be determined to handle the provided "
"credentials."
msgstr "指定された認証情報を処理する認証バックエンドが決定できませんでした。"

#: openstack_auth/backend.py:155
msgid "You are not authorized for any projects."
msgstr "どのプロジェクトに対しても権限がありません。"

#: openstack_auth/backend.py:157
msgid "You are not authorized for any projects or domains."
msgstr "どのプロジェクトやドメインに対しても権限がありません。"

#: openstack_auth/forms.py:51
msgid "Region"
msgstr "リージョン"

#: openstack_auth/forms.py:53
msgid "User Name"
msgstr "ユーザー名"

#: openstack_auth/forms.py:55
msgid "Password"
msgstr "パスワード"

#: openstack_auth/forms.py:69 openstack_auth/forms.py:78
msgid "Domain"
msgstr "ドメイン"

#: openstack_auth/forms.py:96
msgid "Authenticate using"
msgstr "使用する認証方法"

#: openstack_auth/plugin/base.py:98
msgid "Unable to retrieve authorized projects."
msgstr "権限を持っているプロジェクトの情報を取得できません。"

#: openstack_auth/plugin/base.py:110
msgid "Unable to retrieve authorized domains."
msgstr "認証されたドメインを取得できません。"

#: openstack_auth/plugin/base.py:129
msgid "Unable to establish connection to keystone endpoint."
msgstr "Keystone エンドポイントへの接続を確立できません。"

#: openstack_auth/plugin/base.py:135
msgid "Invalid credentials."
msgstr "無効な認証情報です。"

#: openstack_auth/plugin/base.py:138
msgid "An error occurred authenticating. Please try again later."
msgstr "認証中にエラーが発生しました。後ほどもう一度お試しください。"

#: openstack_auth/plugin/k2k.py:84
msgid "Could not find service provider ID on Keystone."
msgstr "Keystone でサービスプロバイダー ID を見つけることができませんでした。"

#: openstack_auth/plugin/k2k.py:105
#, python-format
msgid "Service provider authentication failed. %s"
msgstr "サービスプロバイダーの認証に失敗しました。%s"

#: openstack_auth/views.py:129
#, python-format
msgid "Please consider changing your password, it will expire in %s minutes"
msgstr ""
"パスワードの変更をお勧めします。今のパスワードはあと %s 分で無効になります。"

#: openstack_auth/views.py:207
#, python-format
msgid "Project switch failed for user \"%(username)s\"."
msgstr "ユーザー \"%(username)s\" のプロジェクト切り替えに失敗しました。"

#: openstack_auth/views.py:226
#, python-format
msgid "Switch to project \"%(project_name)s\" successful."
msgstr "プロジェクト \"%(project_name)s\" へ正常に切り替えました。"

#: openstack_auth/views.py:273
msgid "K2K Federation not setup for this session"
msgstr "このセッションには K2K フェデレーションは設定されていません。"

#: openstack_auth/views.py:322
#, python-format
msgid "Switch to Keystone Provider \"%(keystone_provider)s\"successful."
msgstr ""
"Keystone プロバイダー \"%(keystone_provider)s\" への切り替えが正常に完了しま"
"した。"
